// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// continentisland_ARG_cpp
Rcpp::List continentisland_ARG_cpp(Rcpp::List args);
RcppExport SEXP _polyIBD_continentisland_ARG_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(continentisland_ARG_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// continentisland_SMC_conditional_cpp
Rcpp::List continentisland_SMC_conditional_cpp(Rcpp::List args);
RcppExport SEXP _polyIBD_continentisland_SMC_conditional_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(continentisland_SMC_conditional_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// SMC_MCMC_cpp
Rcpp::List SMC_MCMC_cpp(Rcpp::List args);
RcppExport SEXP _polyIBD_SMC_MCMC_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SMC_MCMC_cpp(args));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_polyIBD_continentisland_ARG_cpp", (DL_FUNC) &_polyIBD_continentisland_ARG_cpp, 1},
    {"_polyIBD_continentisland_SMC_conditional_cpp", (DL_FUNC) &_polyIBD_continentisland_SMC_conditional_cpp, 1},
    {"_polyIBD_SMC_MCMC_cpp", (DL_FUNC) &_polyIBD_SMC_MCMC_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_polyIBD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
