# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

continentisland_ARG_cpp <- function(args) {
    .Call(`_polyIBD_continentisland_ARG_cpp`, args)
}

continentisland_SMC_conditional_cpp <- function(args) {
    .Call(`_polyIBD_continentisland_SMC_conditional_cpp`, args)
}

SMC_MCMC_cpp <- function(args) {
    .Call(`_polyIBD_SMC_MCMC_cpp`, args)
}

