# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

continentisland_ARG_cpp <- function(args) {
    .Call(`_polyIBD_continentisland_ARG_cpp`, args)
}

continentisland_SMC_conditional_cpp <- function(args) {
    .Call(`_polyIBD_continentisland_SMC_conditional_cpp`, args)
}

runMCMC_cpp <- function(args, args_functions) {
    .Call(`_polyIBD_runMCMC_cpp`, args, args_functions)
}

